
#   from = "/api/*"
#   to = "http://api-food.com/api/:splat"
#   status = 200
[[redirects]]
  from = "/asd"
  to = "https://www.google.ro/"
  status = 200

# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200