[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "http://api-food.com/api/:splat"
  status = 301
  force = true

# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200